version: '3'

services:
  homeassistant:
    image: homeassistant/home-assistant
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volumes/config:/config
    restart: always
    network_mode: host
